[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[[constraint]]
  name = "github.com/christianrondeau/go-wit"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/Krognol/go-wolfram"
